artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shriadke/PuneHousePricePrediction/raw/main/data/raw_data/Pune_Real_Estate_Data.zip 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["Pune_Real_Estate_Data.xlsx"]
  ALL_REQUIRED_FEAT: ["Price in Millions", "Sub-Area", "Propert Type", "Property Area in Sq. Ft.", "TownShip Name/ Society Name", "Company Name"] # Important features

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  random_seed: 42
  test_ratio: 0.2
  cat_feat: ["Location", "Developer", "Name"]
  num_feat: ["Area_sqft","Loc_trend"]

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation
  model_ckpt: lrmodel.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/
  model_path: artifacts/model_trainer/lrmodel.pkl